image:
    file: .gitpod.Dockerfile
tasks:
  - before: git clone  https://github.com/LambdaTest/lambdatest-cypress-cli && cd lambdatest-cypress-cli 
    init: echo "npm link"
    command: npm i && npm link && cd ..